### ISSUE TITLE
Link to the site mentioned in the presentation

### ISSUE THREAD

**Issue by jakubsadura** [rogeliog/jest-snapshot-talk#2]
Hi,
Would you be so kind to share link to the site about testing mentioned in the presentation?

Cheers

**Comment by rogeliog** [comment]
Hi, sorry which site?

**Comment by jakubsadura** [comment]
I must have mistaken your talk with some other I was watching the same day 😕 I've just watched your talk again and there is no mention, sorry for raising this issue and thanks for response
